trigger:
  branches:
    include:
      - "master"

variables:
  - group: AMLVariables

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Prepare
    displayName: Prepare Conda Environment
    jobs:
      - template: "create_environment.yml"

  - stage: Training_Model
    displayName: AML Training Experiment
    jobs:
      - template: "train_model.yml"

  - stage: Deploy
    displayName: Deploying into container
    jobs:
      - template: "deploy_pipeline.yml"
