AZURE_STORAGE_ACCOUNT_KEY = "AZURE_STORAGE_ACCOUNT_KEY"
AZURE_STORAGE_ACCOUNT_NAME = "AZURE_STORAGE_ACCOUNT_NAME"
MODEL_NAME_VARIABLE = "MODEL_NAME_VARIABLE"

AML_ENVIRONMENT_NAME = "sklearn_environment"
AML_EXPERIMENT_NAME = 'iris_experiment'
AML_COMPUTE_NAME = 'vm-compute'

TRAINING_CONTAINER = 'raw'
SCORING_CONTAINER = 'score'
TRAINING_DATASTORE = 'train'

MODEL_NAME = 'iris_model'
DEPLOYMENT_SERVICE_NAME = "aci-service"





